// ============================================
// Upload Page
// Version: V2608201
// Purpose: File upload with in-app template download, sample data,
//          and row-level data quality feedback
// ============================================

import React, { useState } from 'react';
import tokenService from '../services/tokenService.js';
import Wizard from './Wizard.jsx';

function Upload({ onNext, onError }) {
  const [loading, setLoading] = useState(false);
  const [file, setFile] = useState(null);
  const [dragActive, setDragActive] = useState(false);
  const [downloadingTemplate, setDownloadingTemplate] = useState(false);
  const [loadingSample, setLoadingSample] = useState(false);
  const [parseResult, setParseResult] = useState(null);
  const [wizardMode, setWizardMode] = useState(false);

  if (wizardMode) {
    return <Wizard onComplete={onNext} onCancel={() => setWizardMode(false)} />;
  }

  const handleDrag = (e) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === 'dragenter' || e.type === 'dragover') {
      setDragActive(true);
    } else if (e.type === 'dragleave') {
      setDragActive(false);
    }
  };

  const handleDrop = (e) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);

    const droppedFiles = e.dataTransfer.files;
    if (droppedFiles && droppedFiles[0]) {
      setFile(droppedFiles[0]);
      setParseResult(null);
    }
  };

  const handleFileChange = (e) => {
    if (e.target.files && e.target.files[0]) {
      setFile(e.target.files[0]);
      setParseResult(null);
    }
  };

  // Download the fillable template generated by the backend
  const handleDownloadTemplate = async () => {
    setDownloadingTemplate(true);
    try {
      const response = await fetch('/api/template', {
        headers: { 'Authorization': tokenService.getAuthHeader() }
      });
      if (!response.ok) throw new Error('Template download failed');

      // Use the server's versioned filename (e.g. FACE-Fabric-Template-V2608204.xlsx)
      const disposition = response.headers.get('Content-Disposition') || '';
      const match = disposition.match(/filename="?([^";]+)"?/i);
      const filename = match ? match[1] : 'FACE-Fabric-Template.xlsx';

      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(url);
    } catch (err) {
      onError(err.message || 'Could not download template');
    } finally {
      setDownloadingTemplate(false);
    }
  };

  // Load the built-in demo dataset (2 sample schools)
  const handleLoadSample = async () => {
    setLoadingSample(true);
    try {
      const response = await fetch('/api/template/sample', {
        headers: { 'Authorization': tokenService.getAuthHeader() }
      });
      if (!response.ok) throw new Error('Could not load sample data');

      const result = await response.json();
      if (result.success) {
        onNext(result.data);
      } else {
        throw new Error(result.error || 'Could not load sample data');
      }
    } catch (err) {
      onError(err.message || 'Could not load sample data');
    } finally {
      setLoadingSample(false);
    }
  };

  const handleUpload = async (e) => {
    e.preventDefault();

    if (!file) {
      onError('Please select a file');
      return;
    }

    if (!file.name.match(/\.(xlsx|xls|xlsm)$/i)) {
      onError('Only .xlsx, .xls and .xlsm files are supported');
      return;
    }

    setLoading(true);
    setParseResult(null);

    try {
      const reader = new FileReader();
      reader.onload = async (event) => {
        try {
          const base64 = event.target.result.split(',')[1];

          const response = await fetch('/api/upload', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'Authorization': tokenService.getAuthHeader()
            },
            body: JSON.stringify({
              filename: file.name,
              data: base64
            })
          });

          const result = await response.json();

          if (!response.ok || !result.success) {
            // Show row-level issues even on hard failure
            if (result.issues && result.issues.length > 0) {
              setParseResult({ failed: true, issues: result.issues });
            }
            throw new Error(result.error || 'Upload failed');
          }

          if (result.issues && result.issues.length > 0) {
            // Parsed OK but with data quality warnings - let user review first
            setParseResult({
              failed: false,
              issues: result.issues,
              data: result.data
            });
          } else {
            // Clean parse - continue immediately
            onNext(result.data);
          }
        } catch (error) {
          onError(error.message || 'Upload failed');
        } finally {
          setLoading(false);
        }
      };
      reader.readAsDataURL(file);
    } catch (error) {
      onError('Failed to read file: ' + error.message);
      setLoading(false);
    }
  };

  return (
    <div className="page-upload">
      <h2>Step 1: Upload Network Configuration File</h2>
      <p className="page-description">Upload your network configuration Excel file to begin</p>

      {/* Template & Sample toolbar */}
      <div style={{
        display: 'flex', gap: '12px', flexWrap: 'wrap', alignItems: 'center',
        background: 'var(--card-bg)',
        border: '1px solid var(--border-color)', borderRadius: '10px',
        padding: '14px 16px', marginBottom: '1.5rem'
      }}>
        <div style={{ flex: '1 1 300px' }}>
          <strong style={{ color: 'var(--extreme-violet)' }}>New customer?</strong>
          <div style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginTop: '2px' }}>
            Download the fillable template (with instructions and dropdowns), or explore the app with sample data.
          </div>
        </div>
        <button
          type="button"
          onClick={handleDownloadTemplate}
          disabled={downloadingTemplate}
          style={{
            padding: '10px 18px', border: 'none', borderRadius: '8px', cursor: 'pointer',
            background: 'linear-gradient(135deg, #7519F9, #5B059C)', color: 'white', fontWeight: 600
          }}
        >
          {downloadingTemplate ? '⏳ Generating…' : '📥 Download Template'}
        </button>
        <button
          type="button"
          onClick={handleLoadSample}
          disabled={loadingSample}
          style={{
            padding: '10px 18px', border: 'none', borderRadius: '8px', cursor: 'pointer',
            background: 'linear-gradient(135deg, #00CC99, #00926b)', color: 'white', fontWeight: 600
          }}
        >
          {loadingSample ? '⏳ Loading…' : '✨ Try Sample Data'}
        </button>
        <button
          type="button"
          onClick={() => setWizardMode(true)}
          style={{
            padding: '10px 18px', border: 'none', borderRadius: '8px', cursor: 'pointer',
            background: 'linear-gradient(135deg, #7D76F2, #5B059C)', color: 'white', fontWeight: 600
          }}
        >
          🧙 Start From Scratch
        </button>
      </div>

      <form onSubmit={handleUpload}>
        <div
          className={`upload-area ${dragActive ? 'active' : ''}`}
          onDragEnter={handleDrag}
          onDragLeave={handleDrag}
          onDragOver={handleDrag}
          onDrop={handleDrop}
        >
          <div className="upload-icon">📁</div>
          <div className="upload-text">Drag and drop your Excel file here</div>
          <div className="upload-subtext">or click to browse</div>
          <input
            type="file"
            accept=".xlsx,.xls,.xlsm"
            onChange={handleFileChange}
            style={{ display: 'none' }}
            id="file-input"
          />
          <label htmlFor="file-input" style={{ cursor: 'pointer', width: '100%' }}>
            <div style={{ cursor: 'pointer' }}>
              {file ? (
                <div>
                  <strong>Selected:</strong> {file.name}
                  <div style={{ fontSize: '0.85rem', marginTop: '0.5rem' }}>
                    Size: {(file.size / 1024).toFixed(2)} KB
                  </div>
                </div>
              ) : (
                <div>Click here to select file</div>
              )}
            </div>
          </label>
        </div>

        {/* Row-level data quality feedback */}
        {parseResult && (
          <div style={{
            marginTop: '1.5rem',
            background: parseResult.failed ? '#fef2f2' : '#fffbeb',
            border: `1px solid ${parseResult.failed ? '#fecaca' : '#fcd34d'}`,
            borderRadius: '10px', padding: '16px'
          }}>
            <strong style={{ color: parseResult.failed ? '#b91c1c' : '#92400e' }}>
              {parseResult.failed
                ? '❌ File could not be processed:'
                : `⚠️ File parsed (${parseResult.data.switchCount} switches, ${parseResult.data.vlanCount} VLAN entries) with ${parseResult.issues.length} data note${parseResult.issues.length > 1 ? 's' : ''}:`}
            </strong>
            <ul style={{ margin: '10px 0 0 1.25rem', fontSize: '0.85rem', lineHeight: 1.7, color: '#555' }}>
              {parseResult.issues.slice(0, 15).map((issue, idx) => (
                <li key={idx}>{issue}</li>
              ))}
              {parseResult.issues.length > 15 && (
                <li style={{ fontStyle: 'italic' }}>…and {parseResult.issues.length - 15} more</li>
              )}
            </ul>
            {!parseResult.failed && (
              <div style={{ marginTop: '12px', display: 'flex', gap: '10px', alignItems: 'center' }}>
                <button
                  type="button"
                  onClick={() => onNext(parseResult.data)}
                  className="btn btn-primary"
                >
                  Continue Anyway →
                </button>
                <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
                  or fix the rows above in Excel and re-upload
                </span>
              </div>
            )}
          </div>
        )}

        <div style={{ marginTop: '2rem' }}>
          <h3>Expected File Format</h3>
          <p>Your Excel file should contain:</p>
          <ul style={{ marginLeft: '2rem', marginTop: '0.5rem' }}>
            <li>One row per switch: SwitchName, SwitchType (L2/L3), SiteID, Location, Closet, MgmtVLAN, DefaultGateway</li>
            <li>VLAN columns on each row: Edge Vlans, Name, Subnet, DeviceType, I-SID</li>
            <li>Extra VLANs for a site on their own rows (SiteID + VLAN columns only)</li>
            <li>Not sure? Use the <strong>Download Template</strong> button above — it includes instructions and an example site</li>
          </ul>
        </div>

        <button type="submit" className="btn btn-primary" disabled={!file || loading} style={{ marginTop: '2rem' }}>
          {loading ? <span>⏳ Processing...</span> : <span>📤 Upload & Parse</span>}
        </button>
      </form>
    </div>
  );
}

export default Upload;
